---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts":
    get:
      summary: List all posts for a user
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Post"
  "/api/users/{user_id}/posts/{post_id}/comments":
    get:
      summary: List all comments for a post
      tags:
      - Comments
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: post_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Comment"
    post:
      summary: Add a comment to a post
      tags:
      - Comments
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: post_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
